# Generated by Django 5.2.8 on 2025-12-05 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('national_id', models.CharField(max_length=50, unique=True, verbose_name='کد ملی')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('father_name', models.CharField(max_length=255, verbose_name='نام پدر')),
                ('phone_number', models.CharField(max_length=50, verbose_name='شماره تماس')),
                ('sheba_number_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره شبا ۱')),
                ('sheba_number_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره شبا ۲')),
                ('card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره کارت')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کشاورز',
                'verbose_name_plural': 'کشاورزان',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=255, verbose_name='نام استان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='نام ناظر')),
                ('national_id', models.BigIntegerField(verbose_name='کد ملی')),
                ('degree', models.CharField(max_length=255, verbose_name='مدرک تحصیلی')),
                ('phone', models.BigIntegerField(verbose_name='شماره تماس')),
                ('shaba_id', models.CharField(max_length=255, verbose_name='شماره شبا')),
                ('bank_name', models.CharField(max_length=255, verbose_name='نام بانک')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت سرکشی (تناژ)')),
                ('supervision_permit', models.CharField(max_length=255, verbose_name='مجوز نظارت')),
                ('lat', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='عرض جغرافیایی')),
                ('lng', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='طول جغرافیایی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ناظر',
                'verbose_name_plural': 'ناظران',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255, verbose_name='نام شهر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='farmer.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('village_name', models.CharField(max_length=255, verbose_name='نام روستا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='farmer.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'روستا',
                'verbose_name_plural': 'روستاها',
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('commitment_number', models.CharField(max_length=50, verbose_name='شماره تعهد')),
                ('amount_of_land', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='میزان زمین (هکتار)')),
                ('withdrawal_amount', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار برداشت پیش\u200cبینی شده')),
                ('date_set', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت تعهد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='common.cropyear', verbose_name='سال زراعی')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد کننده')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='farmer.farmer', verbose_name='کشاورز')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='farmer.village', verbose_name='روستا')),
            ],
            options={
                'verbose_name': 'تعهد کشاورز',
                'verbose_name_plural': 'تعهدات کشاورزان',
            },
        ),
    ]
