# Generated by Django 5.2.8 on 2025-12-05 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('farmer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان پرداخت')),
                ('date', models.DateTimeField(verbose_name='تاریخ پرداخت')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_payments', to='common.cropyear', verbose_name='سال زراعی')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_payments', to='common.factory', verbose_name='کارخانه')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مسئول پرداخت')),
            ],
            options={
                'verbose_name': 'پرداخت کارخانه',
                'verbose_name_plural': 'پرداخت\u200cهای کارخانه',
                'db_table': 'factory_payment',
            },
        ),
        migrations.CreateModel(
            name='FarmersGuarantee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('guarantee_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مبلغ ضمانت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_guarantees', to='common.cropyear', verbose_name='سال زراعی')),
                ('guaranteed_farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees_received', to='farmer.farmer', verbose_name='کشاورز ضمانت\u200cشده')),
                ('guarantor_farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees_given', to='farmer.farmer', verbose_name='کشاورز ضامن')),
            ],
            options={
                'verbose_name': 'ضمانت کشاورز',
                'verbose_name_plural': 'ضمانت\u200cهای کشاورزان',
                'db_table': 'farmers_guarantee',
            },
        ),
        migrations.CreateModel(
            name='FarmersPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مبلغ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_payments', to='common.cropyear', verbose_name='سال زراعی')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_payments', to='farmer.farmer', verbose_name='کشاورز')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers_payments', to='common.paymentreason', verbose_name='نوع پرداخت')),
            ],
            options={
                'verbose_name': 'پرداخت کشاورز',
                'verbose_name_plural': 'پرداخت\u200cهای کشاورزان',
                'db_table': 'farmers_payment',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sugar_amount_per_ton_kg', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار شکر به ازای تن (کیلوگرم)')),
                ('sugar_price_per_kg', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='قیمت شکر به ازای کیلوگرم')),
                ('pulp_amount_per_ton_kg', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار تفاله به ازای تن (کیلوگرم)')),
                ('pulp_price_per_kg', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='قیمت تفاله به ازای کیلوگرم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='common.cropyear', verbose_name='سال زراعی')),
            ],
            options={
                'verbose_name': 'قیمت محصول',
                'verbose_name_plural': 'قیمت\u200cهای محصول',
            },
        ),
        migrations.CreateModel(
            name='PurityPrice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base_purity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='خلوص پایه (درصد)')),
                ('base_purity_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='قیمت خلوص پایه')),
                ('price_difference', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='اختلاف قیمت خلوص')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purity_prices', to='common.cropyear', verbose_name='سال زراعی')),
            ],
            options={
                'verbose_name': 'قیمت خلوص',
                'verbose_name_plural': 'قیمت\u200cهای خلوص',
            },
        ),
        migrations.CreateModel(
            name='FarmersInvoicePayed',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payed', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_invoices', to='common.cropyear', verbose_name='سال زراعی')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_invoices', to='farmer.farmer', verbose_name='کشاورز')),
            ],
            options={
                'verbose_name': 'فاکتور پرداخت\u200cشده کشاورز',
                'verbose_name_plural': 'فاکتورهای پرداخت\u200cشده کشاورزان',
                'db_table': 'farmers_invoice_payed',
                'unique_together': {('farmer', 'crop_year')},
            },
        ),
    ]
