# Generated by Django 5.2.8 on 2025-12-05 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorySugar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sugar_weight_received_factory', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='وزن شکر دریافتی')),
                ('sugar_price_received_factory', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='قیمت شکر دریافتی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_sugar', to='common.cropyear', verbose_name='سال زراعی')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_sugar', to='common.factory', verbose_name='کارخانه')),
            ],
            options={
                'verbose_name': 'شکر کارخانه',
                'verbose_name_plural': 'شکر کارخانه',
            },
        ),
        migrations.CreateModel(
            name='FactoryWaste',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('waste_weight_received_factory', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='وزن ضایعات دریافتی')),
                ('waste_price_received_factory', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='قیمت ضایعات دریافتی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_waste', to='common.cropyear', verbose_name='سال زراعی')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_waste', to='common.factory', verbose_name='کارخانه')),
            ],
            options={
                'verbose_name': 'ضایعات کارخانه',
                'verbose_name_plural': 'ضایعات کارخانه',
            },
        ),
        migrations.CreateModel(
            name='FarmersSugarDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sugar_delivered', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='شکر تحویل داده شده')),
                ('sugar_deposit_amount', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار ودیعه شکر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugar_deliveries', to='common.cropyear', verbose_name='سال زراعی')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugar_deliveries', to='farmer.farmer', verbose_name='کشاورز')),
            ],
            options={
                'verbose_name': 'تحویل شکر کشاورز',
                'verbose_name_plural': 'تحویل شکر کشاورزان',
            },
        ),
        migrations.CreateModel(
            name='FarmersWasteDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('waste_delivered', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='ضایعات تحویل داده شده')),
                ('waste_deposit_amount', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار ودیعه ضایعات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_waste_deliveries', to='common.cropyear', verbose_name='سال زراعی')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_deliveries', to='farmer.farmer', verbose_name='کشاورز')),
            ],
            options={
                'verbose_name': 'تحویل ضایعات کشاورز',
                'verbose_name_plural': 'تحویل ضایعات کشاورزان',
            },
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pesticide_name', models.CharField(max_length=255, verbose_name='نام سم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measure_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesticides', to='common.measureunit', verbose_name='واحد اندازه\u200cگیری')),
            ],
            options={
                'verbose_name': 'سموم',
                'verbose_name_plural': 'انواع سموم',
            },
        ),
        migrations.CreateModel(
            name='FarmersPesticide',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pesticide_amount', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار سم')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='قیمت کل')),
                ('price_for_all_farmers_check', models.BooleanField(default=False, verbose_name='بررسی قیمت برای همه کشاورزان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesticides_distributed', to='farmer.commitment', verbose_name='تعهد')),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_pesticides', to='common.cropyear', verbose_name='سال زراعی')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_pesticides', to='common.factory', verbose_name='کارخانه توزیع کننده')),
                ('pesticide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_pesticides', to='inventory.pesticide', verbose_name='سم توزیع شده')),
            ],
            options={
                'verbose_name': 'سم توزیع شده به کشاورز',
                'verbose_name_plural': 'سموم توزیع شده',
            },
        ),
        migrations.CreateModel(
            name='FactoryPesticide',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار موجودی')),
                ('farmer_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='قیمت برای کشاورز')),
                ('factory_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='قیمت برای کارخانه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_pesticides', to='common.cropyear', verbose_name='سال زراعی')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_pesticides', to='common.factory', verbose_name='کارخانه')),
                ('pesticide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_pesticides', to='inventory.pesticide', verbose_name='سم')),
            ],
            options={
                'verbose_name': 'سموم کارخانه',
                'verbose_name_plural': 'سموم کارخانه',
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seed_name', models.CharField(max_length=255, verbose_name='نام بذر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measure_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeds', to='common.measureunit', verbose_name='واحد اندازه\u200cگیری')),
            ],
            options={
                'verbose_name': 'بذر',
                'verbose_name_plural': 'انواع بذر',
            },
        ),
        migrations.CreateModel(
            name='FarmersSeed',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seed_amount', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار بذر')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='قیمت کل')),
                ('price_for_all_farmers_check', models.BooleanField(default=False, verbose_name='بررسی قیمت برای همه کشاورزان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeds_distributed', to='farmer.commitment', verbose_name='تعهد')),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_seeds', to='common.cropyear', verbose_name='سال زراعی')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_seeds', to='common.factory', verbose_name='کارخانه توزیع کننده')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_seeds', to='inventory.seed', verbose_name='بذر توزیع شده')),
            ],
            options={
                'verbose_name': 'بذر توزیع شده به کشاورز',
                'verbose_name_plural': 'بذرهای توزیع شده',
            },
        ),
        migrations.CreateModel(
            name='FactorySeed',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار موجودی')),
                ('farmer_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='قیمت برای کشاورز')),
                ('factory_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='قیمت برای کارخانه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_seeds', to='common.cropyear', verbose_name='سال زراعی')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_seeds', to='common.factory', verbose_name='کارخانه')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_seeds', to='inventory.seed', verbose_name='بذر')),
            ],
            options={
                'verbose_name': 'بذر کارخانه',
                'verbose_name_plural': 'بذرهای کارخانه',
            },
        ),
    ]
