# Generated by Django 5.2.8 on 2025-12-05 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSmsJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=36, verbose_name='شناسه کار')),
                ('status', models.CharField(max_length=20, verbose_name='وضعیت')),
                ('pattern_code', models.CharField(max_length=50, verbose_name='کد الگو')),
                ('total_farmers', models.IntegerField(verbose_name='کل کشاورزان')),
                ('processed_farmers', models.IntegerField(verbose_name='پردازش شده')),
                ('succeeded_farmers', models.IntegerField(verbose_name='موفق')),
                ('failed_farmers', models.IntegerField(verbose_name='ناموفق')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اتمام')),
                ('farmer_ids', models.JSONField(blank=True, null=True, verbose_name='شناسه\u200cهای کشاورزان (همه)')),
                ('succeeded_farmer_ids', models.JSONField(blank=True, null=True, verbose_name='شناسه\u200cهای موفق')),
                ('failed_farmer_ids', models.JSONField(blank=True, null=True, verbose_name='شناسه\u200cهای ناموفق')),
                ('failed_sms_details', models.JSONField(blank=True, null=True, verbose_name='جزئیات خطای پیامک')),
                ('config_json', models.JSONField(blank=True, null=True, verbose_name='تنظیمات پیکربندی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عملیات پیامک انبوه',
                'verbose_name_plural': 'عملیات\u200cهای پیامک انبوه',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='نام ماشین')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ماشین',
                'verbose_name_plural': 'ماشین\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Carriage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('loading_date', models.CharField(max_length=10, verbose_name='تاریخ بارگیری')),
                ('weight', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='وزن محموله')),
                ('origin_id', models.BigIntegerField(verbose_name='شناسه مبدا')),
                ('destination_id', models.BigIntegerField(verbose_name='شناسه مقصد')),
                ('carriage_fee_per_ton', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='هزینه حمل به ازای تن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriages', to='common.cropyear', verbose_name='سال زراعی')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriages', to='farmer.farmer', verbose_name='کشاورز')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carriages', to='farmer.village', verbose_name='روستا')),
            ],
            options={
                'verbose_name': 'حمل و نقل',
                'verbose_name_plural': 'حمل و نقل\u200cها',
                'db_table': 'carriage',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('license_plate', models.CharField(max_length=255, verbose_name='پلاک')),
                ('capacity_ton', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='ظرفیت (تن)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='logistic.car', verbose_name='ماشین')),
            ],
            options={
                'verbose_name': 'راننده',
                'verbose_name_plural': 'راننده\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CarriageStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('carriage_status', models.CharField(max_length=255, verbose_name='وضعیت')),
                ('carried', models.BooleanField(default=False, verbose_name='حمل شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carriage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='logistic.carriage', verbose_name='حمل و نقل')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carriage_statuses', to='logistic.driver', verbose_name='راننده')),
            ],
            options={
                'verbose_name': 'وضعیت حمل و نقل',
                'verbose_name_plural': 'وضعیت\u200cهای حمل و نقل',
            },
        ),
        migrations.CreateModel(
            name='FactoryCommitmentTonnage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('committed_tonnage_amount', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار تناژ تعهد شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_commitment_tonnages', to='common.cropyear', verbose_name='سال زراعی')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitment_tonnages', to='common.factory', verbose_name='کارخانه')),
            ],
            options={
                'verbose_name': 'تعهد تناژ کارخانه',
                'verbose_name_plural': 'تعهدات تناژ کارخانه',
                'db_table': 'factory_commitment_tonnage',
            },
        ),
        migrations.CreateModel(
            name='FarmersLoad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=10, verbose_name='تاریخ بارگیری')),
                ('load_number', models.CharField(max_length=50, verbose_name='شماره بار')),
                ('driver_name', models.CharField(max_length=255, verbose_name='نام راننده')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تلفن راننده')),
                ('total_weight', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='وزن کل (تناژ)')),
                ('dirt_weight', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='وزن ناخالصی (خاک)')),
                ('pest_weight', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='وزن ناخالصی (آفت)')),
                ('pure_weight', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='وزن خالص')),
                ('sugar_beet_polarity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='خلوص (پولاریزاسیون) چغندر')),
                ('price_per_kilo', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='قیمت بر کیلو')),
                ('rent_help', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='کمک هزینه کرایه')),
                ('transportation_cost', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='هزینه حمل و نقل')),
                ('quota_sugar_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='قیمت سهمیه شکر')),
                ('quota_pulp_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='قیمت سهمیه تفاله')),
                ('pure_payable', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='خالص قابل پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_loads', to='common.cropyear', verbose_name='سال زراعی')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='common.factory', verbose_name='کارخانه')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='farmer.farmer', verbose_name='کشاورز')),
            ],
            options={
                'verbose_name': 'بارگیری کشاورز',
                'verbose_name_plural': 'بارگیری کشاورزان',
                'db_table': 'farmers_load',
            },
        ),
    ]
